// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBtFaAiIru85VK35JWCM88T6SFeEzufnQ',
    appId: '1:115037874052:web:b89676ccd35570833a1fd1',
    messagingSenderId: '115037874052',
    projectId: 'princ-3f73c',
    authDomain: 'princ-3f73c.firebaseapp.com',
    storageBucket: 'princ-3f73c.appspot.com',
    measurementId: 'G-Z3GC0YCN9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsoQCwZVOmLvuOnC_MZxDzFSihM_PwEU',
    appId: '1:115037874052:android:34a3a1e8f0b539233a1fd1',
    messagingSenderId: '115037874052',
    projectId: 'princ-3f73c',
    storageBucket: 'princ-3f73c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcrXQTO1wLxsVK4Hj4gi0Y1-h31RQij5A',
    appId: '1:115037874052:ios:350a8430dd0cf8083a1fd1',
    messagingSenderId: '115037874052',
    projectId: 'princ-3f73c',
    storageBucket: 'princ-3f73c.appspot.com',
    iosClientId: '115037874052-v5dajhmlfqp0q27n19gdtg7g48aa4bri.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackPrinceton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcrXQTO1wLxsVK4Hj4gi0Y1-h31RQij5A',
    appId: '1:115037874052:ios:95220d996f1a019d3a1fd1',
    messagingSenderId: '115037874052',
    projectId: 'princ-3f73c',
    storageBucket: 'princ-3f73c.appspot.com',
    iosClientId: '115037874052-do51ju0gokn2eas5ple4udc6uspikmi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackPrinceton.RunnerTests',
  );
}
